### PR TITLE
update to framework v5

### PR DESCRIPTION
**Pull request by chucklorenz**
This PR makes Flipcard compatible with framework version v5. Significant impact due to new naming convention for CSS class names.

Hope this helps!!

### CODE REVIEW

**Review by chetan-hajare — APPROVED** [review]
Thank you @chucklorenz for taking this up 👍

**Comment by rakeshkumar749** [comment]
During the preview of course, Adapt.min.js file generate the error "Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined" if I use this component in my course. can you please check and resolve this.

**Comment by chetan-hajare** [comment]
> During the preview of course, Adapt.min.js file generate the error "Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined" if I use this component in my course. can you please check and resolve this.

Sure, Could you please help with the framework version?

**Comment by yana-garcia** [comment]
Hi, I encounter same error. What is the possible cause of this? Thanks.

**Comment by rakeshkumar749** [comment]
may this component is not compatible with the updated adapt tool. this component required some modification. also this.model.reset(isResetOnRevisit); is showing undefined in adapt-contrib-flipcard.js.

**Comment by rakeshkumar749** [comment]
> Hi, I encounter same error. What is the possible cause of this? Thanks.

do you have used/know any other similar component for flipping, which are compatible with updated adapt tool?

**Comment by yana-garcia** [comment]
CLI: 2.1.9
Framework: 5.4.0

this is may adapt version as of now

**Comment by yana-garcia** [comment]
> > Hi, I encounter same error. What is the possible cause of this? Thanks.
> 
> do you have used/know any other similar component for flipping, which are compatible with updated adapt tool?

Unfortunately, I'm still exploring adapt and has a few knowledge about the components. And I don't know any other similar component to flipping. sorry

**Comment by oliverfoster** [comment]
PR to fix in framework: https://github.com/adaptlearning/adapt_framework/pull/2788

This line is deprecated https://github.com/ExultCorp/adapt-contrib-flipcard/blob/master/js/adapt-contrib-flipcard.js#L156

image


You need to register a model such as:

```js
/*
 * adapt-contrib-flipcard
 * License - https://github.com/ExultCorp/adapt-contrib-flipcard/blob/master/LICENSE
 * Maintainers - Himanshu Rajotia <himanshu.rajotia@exultcorp.com>
 */
define([
    'core/js/models/componentModel', // add this
    'core/js/views/componentView', // change these to use proper paths
    'core/js/adapt'
], function(ComponentModel, ComponentView, Adapt) {

     // missing code

    Adapt.register('flipcard', {
      model: ComponentModel.extend({}), // register the model
      view: Flipcard
    });

    return Flipcard;

});
```

**Comment by rakeshkumar749** [comment]
Thanks. it is working now.

**Pull request merged**
